x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

services:
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - stats

  prometheus:
    image: prom/prometheus:v2.51.2
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging
    networks:
      - stats
    
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/data:/var/lib/grafana
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
      - ./etc/dashboards:/etc/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    depends_on:
      - loki
      - prometheus
    logging: *default-logging
    networks:
      - stats

  fruitygitserver:
    build:
      context: .
      dockerfile: FruityGitServer/Dockerfile
    ports:
      - "8000:8080"
    networks:
      - stats
    depends_on:
      loki:
        condition: service_started
    logging: *default-logging
        

networks:
  stats:
    driver: bridge  
